name: Publish Book Daily

on:
    push:
        branches: [main]
    schedule:
        - cron: "0 0 1 * *"
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Get current date
              id: date
              run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
            - uses: actions/checkout@v2
            - name: Setup Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest
            - run: bun install
            - run: bunx playwright install --with-deps
            - run: bun start

            - uses: "marvinpinto/action-automatic-releases@latest"
              with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  automatic_release_tag: release-${{ steps.date.outputs.date }}
                  prerelease: false
                  title: Release ${{ steps.date.outputs.date }}
                  files: |
                      output/*.pdf
